05-11 18:20:30 jdbc[1424]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.addRow(aSimpleDB.java:308)
	at aurora.V1.core.Updater.updateAuroraCoverDB(Updater.java:80)
	at aurora.V1.core.Updater.<init>(Updater.java:46)
	at aurora.V1.core.Updater.main(Updater.java:41)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
05-11 20:09:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:229)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:316)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-11 20:09:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:181)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-11 20:09:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:196)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:112)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:188)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-12 22:28:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:229)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:316)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-12 22:28:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:196)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:112)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:188)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-12 22:28:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:181)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-12 22:32:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:32:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:35:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:35:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:35:31 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
05-12 22:35:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:42:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:836)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
05-12 22:42:31 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-164]
05-12 22:42:35 jdbc[9]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.getRowFlex(aSimpleDB.java:661)
	at aurora.V1.core.GameSearch.searchSpecificGame(GameSearch.java:155)
	at aurora.V1.core.Aurora_GameLibrary$SelectListHandler.valueChanged(Aurora_GameLibrary.java:985)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1765)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1779)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:167)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:147)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:194)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:388)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:398)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:442)
	at javax.swing.JList.setSelectionInterval(JList.java:2035)
	at javax.swing.plaf.basic.BasicListUI$Handler.adjustSelection(BasicListUI.java:2727)
	at javax.swing.plaf.basic.BasicListUI$Handler.mousePressed(BasicListUI.java:2683)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:263)
	at java.awt.Component.processMouseEvent(Component.java:6285)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6053)
	at java.awt.Container.processEvent(Container.java:2041)
	at java.awt.Component.dispatchEventImpl(Component.java:4651)
	at java.awt.Container.dispatchEventImpl(Container.java:2099)
	at java.awt.Component.dispatchEvent(Component.java:4481)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4235)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
	at java.awt.Container.dispatchEventImpl(Container.java:2085)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4481)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:643)
	at java.awt.EventQueue.access$000(EventQueue.java:84)
	at java.awt.EventQueue$1.run(EventQueue.java:602)
	at java.awt.EventQueue$1.run(EventQueue.java:600)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$2.run(EventQueue.java:616)
	at java.awt.EventQueue$2.run(EventQueue.java:614)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:613)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 55 more
05-13 01:14:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:229)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:316)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-13 01:14:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:181)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
05-13 01:14:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-162]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:596)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:310)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:384)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:264)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:251)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:201)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:196)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:112)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:188)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1411)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1991)
06-07 09:40:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "AURORATABLE" already exists; SQL statement:
CREATE TABLE AuroraTable [42101-164]
06-07 09:40:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "GAME_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD Game_Name VARCHAR_IGNORECASE(255) [42121-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:292)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:205)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:141)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:55)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
06-07 09:40:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "FILE_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD File_Name VARCHAR_IGNORECASE(255) [42121-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:292)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:205)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:141)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:56)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
06-07 09:47:21 jdbc[1423]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.addRow(aSimpleDB.java:308)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:80)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
07-01 12:43:26 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
07-01 12:43:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 22:50:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "AURORATABLE" already exists; SQL statement:
CREATE TABLE AuroraTable [42101-167]
08-18 22:50:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "GAME_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD Game_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:55)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 22:50:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "FILE_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD File_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:56)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 22:51:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%need%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
08-18 22:51:47 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
08-18 23:01:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "AURORATABLE" already exists; SQL statement:
CREATE TABLE AuroraTable [42101-167]
08-18 23:01:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "GAME_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD Game_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:55)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 23:01:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "FILE_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD File_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:56)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 23:03:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:03:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:03:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%Tungl%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
08-18 23:05:06 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:07:08 jdbc[1350]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.addRow(aSimpleDB.java:308)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:80)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
08-18 23:09:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:10:33 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:10:33 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:11:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:11:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:12:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%counter%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
08-18 23:13:01 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
08-18 23:13:03 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:13:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
08-18 23:21:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "AURORATABLE" already exists; SQL statement:
CREATE TABLE AuroraTable [42101-167]
08-18 23:21:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "GAME_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD Game_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:55)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 23:21:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "FILE_NAME"; SQL statement:
ALTER TABLE AuroraTable ADD File_Name VARCHAR_IGNORECASE(255) [42121-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:377)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:552)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:303)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at aurora.engine.V1.Logic.aSimpleDB.addColumn(aSimpleDB.java:280)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:56)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
08-18 23:30:47 jdbc[1349]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.addRow(aSimpleDB.java:308)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:80)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
09-04 21:42:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-04 21:46:01 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-04 21:46:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-04 21:58:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1383)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:836)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:219)
	at aurora.V1.core.GameSearch.run(GameSearch.java:302)
	at java.lang.Thread.run(Thread.java:662)
09-07 21:47:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-07 21:47:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-17 23:44:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-17 23:48:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
09-17 23:48:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-03 23:32:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%border%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:221)
	at aurora.V1.core.GameSearch.run(GameSearch.java:305)
	at java.lang.Thread.run(Thread.java:662)
10-06 13:49:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%Borderl%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:221)
	at aurora.V1.core.GameSearch.run(GameSearch.java:305)
	at java.lang.Thread.run(Thread.java:662)
10-06 13:49:52 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:221)
	at aurora.V1.core.GameSearch.run(GameSearch.java:305)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
10-06 13:49:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 13:49:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 13:49:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:26 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%Borderlansd %' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.aSimpleDB.searchAprox(aSimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:221)
	at aurora.V1.core.GameSearch.run(GameSearch.java:305)
	at java.lang.Thread.run(Thread.java:662)
10-06 18:15:27 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:27 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:27 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:28 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 18:15:28 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
10-06 19:00:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-18 20:43:20 jdbc[1400]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.ASimpleDB.addRow(ASimpleDB.java:308)
	at aurora.V1.core.DBUpdater.updateAuroraCoverDB(DBUpdater.java:80)
	at aurora.V1.core.DBUpdater.<init>(DBUpdater.java:46)
	at aurora.V1.core.DBUpdater.main(DBUpdater.java:41)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
11-26 22:22:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:19 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:19 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT FILE_NAME FROM AuroraTable WHERE GAME_NAME LIKE '%asd%' [57014-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.engine.Session.checkCanceled(Session.java:884)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:274)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:332)
	at org.h2.command.dml.Select.queryFlat(Select.java:514)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at aurora.engine.V1.Logic.ASimpleDB.searchAprox(ASimpleDB.java:838)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:245)
	at aurora.V1.core.GameSearch.run(GameSearch.java:337)
	at java.lang.Thread.run(Thread.java:662)
11-26 22:22:23 jdbc[10]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.ASimpleDB.searchAprox(ASimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:243)
	at aurora.V1.core.GameSearch.run(GameSearch.java:337)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
11-26 22:22:23 jdbc[10]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)
	at aurora.engine.V1.Logic.ASimpleDB.searchAprox(ASimpleDB.java:818)
	at aurora.V1.core.GameSearch.searchGame(GameSearch.java:243)
	at aurora.V1.core.GameSearch.run(GameSearch.java:337)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
11-26 22:22:23 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:22:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:40:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:41:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
11-26 22:41:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-167]
